### ISSUE TITLE
Docker Deemix creating a folder for each artist doesn't work.

### ISSUE THREAD

**Issue by Tihass1975** [bambanah/deemix#158]
**Describe the bug**
If I check the option create a folder for each artist in the UI %artist% it is ignored.

**To Reproduce**
1.  Go to settings in the UI and set the option create a Folder for each artist %artist% and save.
2.  Download a album of a artist, create only a folder for the Album.
3.  Restart the docker can´t resolve the Problem.

I have deployed the docker image with this Compose YAML:

```
services:
  deemix:
    container_name: Deemix
    image: ghcr.io/bambanah/deemix:latest
    volumes:
      - /srv/dev-disk-by-uuid-bdfc101a-3a86-4936-8376-aaa6342121cb/files/musik:/downloads
      - /srv/dev-disk-by-uuid-70ab5780-c50a-4f11-8da3-253d9b43d0b2/docker/deemix/config:/config
    networks:
      mvl:
        ipv4_address: 192.168.178.40
    environment:
      PUID: 1000  
      PGID: 100  
    restart: unless-stopped  

networks:
  mvl:
    external: true  
```

I have set the permissions for the folders: musik and config

```
tihass=1000 users=100

chown -R tihass:users musik
chown -R tihass:users config
chmod -R 777 musik
chmod -R 777 config

```

Logs from the Docker:

```
To support LSIO projects visit:

https://www.linuxserver.io/donate/

───────────────────────────────────────

GID/UID

───────────────────────────────────────

User UID:    1000

User GID:    100

───────────────────────────────────────

[cont-init.d] Testing Access

[cont-init.d] Download Folder Write Access          : Success 

[cont-init.d] Config Folder Write Access            : Success 

[cont-init.d] Internet Access                       : Success 

[custom-init] No custom files found, skipping...

[ls.io-init] done.

[services.d] Starting Deemix

(node:169) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time

(Use `node --trace-warnings ...` to show where the warning was created)
```
