### ISSUE TITLE
ENV Var DEEMIX_MUSIC_DIR does not update the download path

### ISSUE THREAD

**Issue by CurlyBorly** [bambanah/deemix#159]
**Describe the bug**
The env var DEEMIX_MUSIC_DIR does not update the value of the download path. Every time I restart the container, is switches back to `/downloads` and I have to manually update it in the GUI.

**To Reproduce**
1. Add DEEMIX_MUSIC_DIR to the docker environment variables and set it to a value other than `/downloads`
2. Start up the container
3. In the logs, observe the Downloads folder is attempting to find the default `/downloads` directory instead of the value set for the env var
4. In Deemix, go to Settings -> Download Path
5. Observe the value is `/downloads`

**Expected behavior**
Changing the value of DEEMIX_MUSIC_DIR should change the Downloads folder value

**Screenshots**
![Screenshot_20250125-135057.png](https://github.com/user-attachments/assets/8f84d148-8b27-4048-844f-c9e30af83dd1)

![Screenshot_20250125-135400.png](https://github.com/user-attachments/assets/c0865403-e029-4184-80cc-2a65394e8a82)

**Additional context**
My docker-compose:
```
deemix:
    image: ghcr.io/bambanah/deemix:latest
    container_name: deemix
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK_SET=002
      - DEEMIX_MUSIC_DIR=/data/deemix
    ports:
      - 6595:6595
    volumes:
      - ${DOCKERCONFDIR}/deemix:/config
      - ${DOCKERSTORAGEDIR}:/data
```
